version: "3.9"
   
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/apiProject:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - .env
    ports: 
      - 3001:3001
    command: python manage.py runserver 0.0.0.0:3001
    restart: always
    depends_on:
      database:
        condition: service_healthy
  
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    restart: always
    ports:
        - 8080:8080
    env_file:
      - .env
    command: start-dev

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/reactProject:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    command: npm start

  database:
    image: postgres:14.5
    volumes:
      - ./database/db:/var/lib/postgresql/data
    env_file:
      - .env                                                
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5 
    